### ISSUE TITLE
Adicionar separador de milhar no resultado do simulador

### ISSUE THREAD

**Issue by LuizBazon** [easynvest/simulador-rendafixa#12]
No resultado do simulador de renda fixa, os valores em reais não possuem separador de milhar, dificultando a visualização dos números.

Atualmente sem separador de milhar

![](https://user-images.githubusercontent.com/14332486/31080313-b744f36c-a75e-11e7-8c75-6ad965f0b684.png)

Como deveria ser com separador de milhar

![](https://user-images.githubusercontent.com/14332486/31080314-b7453642-a75e-11e7-8db5-d2fe847708f8.png)

**Comment by lucasdaiki** [comment]
Boa, posso dar um gás nisso ae :)
