### ISSUE TITLE
Retirar vírgulas desnecessárias de valores

### ISSUE THREAD

**Issue by diegoeis** [easynvest/simulador-rendafixa#16]
Existem alguns valores na tela de resultados que estão aparecendo com vírgula, mas que não deveriam ter. Esse bug apareceu logo depois da PR do #14:

- Valor aplicado inicialmente
- Dias corridos
- Percentual do CDI do investimento
- Rentabilidade anual

**Comment by lucasdaiki** [comment]
Pesso perdau pelo vassilo
Já tô corrigindo hehe

**Comment by lucasdaiki** [comment]
PR https://github.com/easynvest/simulador-rendafixa/pull/19
