### ISSUE TITLE
Semantic Version & CHANGELOG

### ISSUE THREAD

**Issue by edmolima** [easynvest/simulador-rendafixa#17]
Temos que usar o padrão de semantic version e adicionar um changelog para o projeto. Assim podemos fazer o controle de tag e ter um controle melhor das versões.

Acham válido começarmos a fazer isso agora e já automatizar?

**Comment by diegoeis** [comment]
Eu acho legal começar o quanto antes para manter a ordem.

**Comment by lucasdaiki** [comment]
PR https://github.com/easynvest/simulador-rendafixa/pull/24
