### ISSUE TITLE
Adicionar estilo de código

### ISSUE THREAD

**Issue by magnobiet** [easynvest/simulador-rendafixa#3]
Adicionar os arquivos [.editorconfig](http://editorconfig.org/) e [.eslintrc.js](https://eslint.org/) com as regras de estilo do projeto.

Minhas sugestões iniciais.

## .editorconfig
```
root = true

[*]
indent_style = tab
indent_size = 4
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[{*.json,.*rc,*.yml,*.yaml}]
indent_style = space
indent_size = 2
```
## .eslintrc.js
```javascript
module.exports = {
	root: true,
	env: {
		es6: true,
		browser: true
	},
	globals: {
		axios: true,
		vanillaTextMask: true,
		createNumberMask: true
	},
	extends: 'eslint:recommended',
	'rules': {
		'indent': ['error', 'tab'],
		'linebreak-style': ['error', 'unix'],
		'no-console': ['error', {
			'allow': ['log', 'warn', 'error', 'debug']
		}],
		'quotes': ['error', 'single'],
		'camelcase': 'error',
		'semi': ['error', 'always'],
		'no-var': ['error']
	}
};
```

**Comment by diegoeis** [comment]
@magnobiet obrigado pela ajuda, cara!

Nós acabamos de colocar esse projeto no ar por conta de uma semana de inovação que fizemos aqui na Easynvest e pra ser sincero, foi uma surpresa que você achou isso aqui. :-D

Bom, subi agora o .editorconfig, a gente vai subir o linter depois, por conta da bagunça que está o código hoje, dado que tínhamos que fazer o projetinho em uma semana. 

Valeu pelo toque!
