### ISSUE TITLE
Colocar API em HTTPS

### ISSUE THREAD

**Issue by lucasdaiki** [easynvest/simulador-rendafixa#35]
<img width="1056" alt="screen shot 2017-10-21 at 12 01 26" src="https://user-images.githubusercontent.com/10747020/31852507-98b86ade-b657-11e7-8a92-1a0925de696e.png">

http://api-simulator-calc.us-east-1.elasticbeanstalk.com/calculator/simulate?investedAmount=10101&maturityDate=2020-10-10&rate=123&index=CDI&isTaxFree=false

**Comment by jukajr** [comment]
já foi alterado para https, favor finalizar a issue
