### ISSUE TITLE
Adicionar screenshot da página principal ao README.md

### ISSUE THREAD

**Issue by edmolima** [easynvest/simulador-rendafixa#40]
Após a URL do simulador rendafixa adicionar screenshot da página incial.

https://easynvest.github.io/simulador-rendafixa/

**Comment by rsarai** [comment]
Posso pegar esse?

**Comment by rafaellucio** [comment]
Pode, com certeza!!

**Comment by AlessandraMitie** [comment]
Aew galera, ta ai meu pull request, façam bom proveito #42
