### ISSUE TITLE
Contagem de dias do site e da API

### ISSUE THREAD

**Issue by leogregianin** [easynvest/simulador-rendafixa#5]
A partir das 21 horas do horário de Brasília (UTC-3) o simulador já calcula os dias corridos como sendo o próximo dia.  Aparentemente o site considera o horário local e a API considera o horário com base no UTC.

Na prática não tem influência pois o investimento só pode ocorrer em horário comercial mas para que o site fique com a mesma informação da API seria interessante que retornassem a mesma informação.

**Comment by edmolima** [comment]
@leogregianin boa vamos conferir, a gente tá lançando o código dá API aos poucos também, talvez um refactoring considerando isso seria interessante. Vou colocar como bug e assim que resolvermos fazemos a referência a issue!

**Comment by bbatalha** [comment]
@diegoeis e @edmolima bem legal o simulador. Fiquei com dificuldade em ler os números por falta de pontuação. Por exemplo R$100.000,00, acho que vai ficar bem melhor para ler o montante. 
Coloquei um screenshot com e outro sem a pontuação da uma olhada.
<img width="647" alt="screen shot 2017-10-02 at 10 44 12" src="https://user-images.githubusercontent.com/14332486/31080314-b7453642-a75e-11e7-8db5-d2fe847708f8.png">
<img width="653" alt="screen shot 2017-10-02 at 10 41 42" src="https://user-images.githubusercontent.com/14332486/31080313-b744f36c-a75e-11e7-8c75-6ad965f0b684.png">

**Comment by LuizBazon** [comment]
Verdade, @bbatalha. Dificulta mesmo a visualização quando o valor chega na casa do milhar.
Criei uma issue específica para isso ser endereçado, ok?

Obrigado!

[https://github.com/easynvest/simulador-rendafixa/issues/12](url)

**Comment by lucasdaiki** [comment]
@bbatalha Tá lá, mano :)

https://github.com/easynvest/simulador-rendafixa/pull/14
