### ISSUE TITLE
Adicionar documentação de convenções de commit

### ISSUE THREAD

**Issue by edmolima** [easynvest/simulador-rendafixa#50]
Adicionar um padrão de mensagens de commits ao projeto é importante para os futuros merges. Um padrão sugerido é da ferramenta: [Karma](https://karma-runner.github.io)

Convenção sugerida:
https://karma-runner.github.io/latest/dev/git-commit-msg.html

**Comment by rafaellucio** [comment]
## Formato da mensagem de commit:

```
<tipo>(<scopo>): <assunto> 

<corpo> 

<rodape>
```

Exemplo de mensagem de commit:

```
fix(auth): Corrige autenticação quando passa o e-mail 

Adiciona uma nova dependencia.

Fixes #2310

```

**Mensagem `<assunto>`:**

A primeira linha não pode passar de 70 caracteres, a segunda linha está sempre em branco e outras linhas devem ser envolvidas em 80 caracteres. O tipo e o escopo sempre devem ser minúsculos como mostrado abaixo.

**Mensagem `<tipo>`**
_Permitidos:_

- feat (nova feature para usuário, não é uma nova feature para build ou scripts)
- fix (bug fix para o usuário, não é uma nova fix para build ou scripts)
- docs (mudança em documentação)
- style (formatação, espaços, identação, etc; sem mudança no código de prod)
- refactor (refatorando código de produção, tal como, renomeando variáveis)
- test (adição de testes, refatorar testes; sem mudança no código de prod)
- chore (atualização de tasks de build, etc; sem mudançao no código de prod)

**Exemplo de `<escopo>`**

- registry-completion
- legacy-wrapper
- symbol-base
- config
- etc.

O <escopo> pode estar vazio (por exemplo, se a mudança for global ou difícil de atribuir a um único componente), caso em que os parênteses são omitidos.

**Mensagem do `<corpo>`**

Usar o imperativo no presente "altera" não "alterado" nem "alterações"
inclui motivação para a mudança e contrasta com o comportamento anterior

**Mensagem do `<rodape>`**

Referenciando `issues`

As issues devem ser listadas e separadas por virgula com o prefixo "Closes"

`Closes #234`

Ou

`Closes #123, #245, #992`

**Referências:**

http://karma-runner.github.io/1.0/dev/git-commit-msg.html
http://365git.tumblr.com/post/3308646748/writing-git-commit-messages
http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
