### ISSUE TITLE
Erro no resultado da simulação quando há casas decimais

### ISSUE THREAD

**Issue by leogregianin** [easynvest/simulador-rendafixa#6]
Em uma simulação com as seguintes informações:
```bash
Quanto você gostaria de aplicar? R$ 1.000,50
Qual a data de vencimento do papel? 31/12/2017
Qual o percentual do CDI do papel? 94,50%
```

O resultado é:

```bash
Resultado da simulação: R$ 472403.57
Rendimento total de R$ 372353.57
Valor aplicado inicialmente: R$ 100050
Valor bruto do investimento: R$ 472403.57
Valor do rendimento: R$ 372353.57
IR sobre o investimento: R$ 83779.55 (22.5 %)
Valor líquido do investimento: R$ 388624.02

Data de resgate: 31/12/2017
Dias corridos: 92
Rendimento mensal: 0.6 %
Percentual do CDI do papel: 9450 %
Rentabilidade anual: 7.4996 %
Rentabilidade no período: 372.17 %
```

O que parece não ser o certo :D isso por causa do tratamento das casas decimais que são enviadas para a API. 

Como está sendo o get hoje: https://easynvestsimulatorcalcapi.azurewebsites.net/calculator/simulate?investedAmount=1000,00&index=CDI&rate=94,50&isTaxFree=false&maturityDate=2017-12-31

E como deveria ser: https://easynvestsimulatorcalcapi.azurewebsites.net/calculator/simulate?investedAmount=1000.0&index=CDI&rate=94.5&isTaxFree=false&maturityDate=2017-12-31

Vou fazer um PR para isso :D

**Comment by lucasdaiki** [comment]
Closed https://github.com/easynvest/simulador-rendafixa/pull/7
