### ISSUE TITLE
Projeto saiu fora do ar?

### ISSUE THREAD

**Issue by charleston10** [easynvest/simulador-rendafixa#77]
O projeto saiu fora do ar?

Não está funcionando
https://easynvest.github.io/simulador-rendafixa/

Queria fazer um projeto pra mim,  fazendo as simulações
Mas a API sempre retorna 500

**Comment by lucasdaiki** [comment]
também to nessa :/ @vappolinario consegue nos ajudar?

**Comment by vappolinario** [comment]
@lucasdaiki @charleston10 problema resolvido.
