### ISSUE TITLE
Sugestões de labels

### ISSUE THREAD

**Issue by lucasdaiki** [easynvest/simulador-rendafixa#8]
Coé, Rapaziada!

Apresentei o simulador para algumas pessoas (leigas) e a maioria me perguntou o que seria um **papel**. 
O que acham de mudarmos o **papel** para algo mais intuitivo? :smile:
Faz sentido?
Caso sim,  **Minha sugestão**: Trocarmos todos os labels de **papel** para **investimento**.

**Comment by LuizBazon** [comment]
Para mim, faz sentido. Papel/título carrega muito do jargão do mercado financeiro.

**Comment by lucasdaiki** [comment]
o que acha manos? @diegoeis @edmolima

**Comment by diegoeis** [comment]
Por mim, manda bala!

**Comment by edmolima** [comment]
@lucasdaiki acho bacana, façamos isso sim!

**Comment by lucasdaiki** [comment]
Acabei subindo sem PR, perdão hehe é nois
